apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  selector:
    project: roboshop
    tier: frontend
    component: frontend
  ports:
  - port: 80
    targetPort: 80
