apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: rabbitmq
spec:
  replicas: 3
  selector:
    matchLabels:
      project: roboshop
      tier: db
      component: rabbitmq
  template:
    metadata:
      labels:
        project: roboshop
        tier: db
        component: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:4.3
        env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq-sec
              key: RABBITMQ_DEFAULT_USER
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq-sec
              key: RABBITMQ_DEFAULT_PASS
        # resources:
        #   requests:
        #     cpu: "250m"
        #     memory: "256Mi"
        #   limits:
        #     cpu: "500m"
        #     memory: "512Mi"
