apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: rabbitmq
spec:
  selector:
    project: roboshop
    tier: db
    component: rabbitmq
  ports:
  - protocol: TCP
    port: 5672
    targetPort: 5672 
  